(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "SENDMESSAGE"
   "<SENDMESSAGE-REQUEST>"
   "SENDMESSAGE-REQUEST"
   "<SENDMESSAGE-RESPONSE>"
   "SENDMESSAGE-RESPONSE"
  ))

