// Generated by gencpp from file beginner_tutorials/SendMessage.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_SENDMESSAGE_H
#define BEGINNER_TUTORIALS_MESSAGE_SENDMESSAGE_H

#include <ros/service_traits.h>


#include <beginner_tutorials/SendMessageRequest.h>
#include <beginner_tutorials/SendMessageResponse.h>


namespace beginner_tutorials
{

struct SendMessage
{

typedef SendMessageRequest Request;
typedef SendMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendMessage
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::SendMessage > {
  static const char* value()
  {
    return "ab7c2a139228f69ecebcc23eb84b1eff";
  }

  static const char* value(const ::beginner_tutorials::SendMessage&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::SendMessage > {
  static const char* value()
  {
    return "beginner_tutorials/SendMessage";
  }

  static const char* value(const ::beginner_tutorials::SendMessage&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::SendMessageRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::SendMessage > 
template<>
struct MD5Sum< ::beginner_tutorials::SendMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::SendMessage >::value();
  }
  static const char* value(const ::beginner_tutorials::SendMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::SendMessageRequest> should match 
// service_traits::DataType< ::beginner_tutorials::SendMessage > 
template<>
struct DataType< ::beginner_tutorials::SendMessageRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::SendMessage >::value();
  }
  static const char* value(const ::beginner_tutorials::SendMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::SendMessageResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::SendMessage > 
template<>
struct MD5Sum< ::beginner_tutorials::SendMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::SendMessage >::value();
  }
  static const char* value(const ::beginner_tutorials::SendMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::SendMessageResponse> should match 
// service_traits::DataType< ::beginner_tutorials::SendMessage > 
template<>
struct DataType< ::beginner_tutorials::SendMessageResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::SendMessage >::value();
  }
  static const char* value(const ::beginner_tutorials::SendMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_SENDMESSAGE_H
