// Generated by gencpp from file beginner_tutorials/String.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_STRING_H
#define BEGINNER_TUTORIALS_MESSAGE_STRING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct String_
{
  typedef String_<ContainerAllocator> Type;

  String_()
    : x()  {
    }
  String_(const ContainerAllocator& _alloc)
    : x(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _x_type;
  _x_type x;





  typedef boost::shared_ptr< ::beginner_tutorials::String_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::String_<ContainerAllocator> const> ConstPtr;

}; // struct String_

typedef ::beginner_tutorials::String_<std::allocator<void> > String;

typedef boost::shared_ptr< ::beginner_tutorials::String > StringPtr;
typedef boost::shared_ptr< ::beginner_tutorials::String const> StringConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::String_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::String_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/lalit/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::String_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::String_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::String_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::String_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::String_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::String_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::String_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e90a477f371ee690ac763e15f14f34b";
  }

  static const char* value(const ::beginner_tutorials::String_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e90a477f371ee69ULL;
  static const uint64_t static_value2 = 0x0ac763e15f14f34bULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::String_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/String";
  }

  static const char* value(const ::beginner_tutorials::String_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::String_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string x\n\
";
  }

  static const char* value(const ::beginner_tutorials::String_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::String_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct String_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::String_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::String_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_STRING_H
